#!/bin/bash

function vpn-connect {
/usr/bin/env osascript <<-EOF
tell application "System Events"
        tell current location of network preferences
                set VPN to service "MyVPN" -- Within the quotes fill in your vpn connection name
                if exists VPN then connect VPN
                repeat while (current configuration of VPN is not connected)
                    delay 1
                end repeat
        end tell
end tell
EOF
}

# Set this to the IP of a device that is always up within your VPN network.
# Usualluy you router will work, but it is best to use a CDR that is not 192.168.0.0/24 or 192.168.1.0/24, since most residential networks will also be on those subnets.
TESTIP="192.168.50.1"

ping -o -t 2 $TESTIP&>/dev/null;
if [[ $? -ne 0 ]]; then
	vpn-connect;
fi
